-- MySQL Script generated by MySQL Workbench
-- Fri Feb  4 19:18:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`LIBROS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LIBROS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LIBROS` (
  `ISBN` INT NOT NULL,
  `Título` VARCHAR(45) NOT NULL,
  `Autor` VARCHAR(45) NULL,
  `Género` VARCHAR(45) NULL,
  `Editorial` VARCHAR(45) NULL,
  `Precio` DOUBLE NULL,
  `FechaPublicacion` DATE NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `DNI` VARCHAR(45) NOT NULL,
  `NumContacto` INT NULL,
  `FechaNac` DATE NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NULL,
  `LibrosExtraibles` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDICION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EDICION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EDICION` (
  `LIBROS_ISBN` INT NOT NULL,
  `NumEdicion` INT NOT NULL,
  `Stock` INT NULL,
  `CLIENTE_DNI_recibe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LIBROS_ISBN`, `NumEdicion`),
  INDEX `fk_EDICION_CLIENTE1_idx` (`CLIENTE_DNI_recibe` ASC) VISIBLE,
  CONSTRAINT `fk_table1_LIBROS`
    FOREIGN KEY (`LIBROS_ISBN`)
    REFERENCES `mydb`.`LIBROS` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EDICION_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI_recibe`)
    REFERENCES `mydb`.`CLIENTE` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIGITAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DIGITAL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DIGITAL` (
  `EDICION_LIBROS_ISBN` INT NOT NULL,
  `EDICION_NumEdicion` INT NOT NULL,
  `Valoracion` DOUBLE NULL,
  `Opiniones` LONGTEXT NULL,
  PRIMARY KEY (`EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`),
  CONSTRAINT `fk_table1_EDICION1`
    FOREIGN KEY (`EDICION_LIBROS_ISBN` , `EDICION_NumEdicion`)
    REFERENCES `mydb`.`EDICION` (`LIBROS_ISBN` , `NumEdicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FISICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FISICO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FISICO` (
  `EDICION_LIBROS_ISBN` INT NOT NULL,
  `EDICION_NumEdicion` INT NOT NULL,
  PRIMARY KEY (`EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`),
  CONSTRAINT `fk_table1_EDICION2`
    FOREIGN KEY (`EDICION_LIBROS_ISBN` , `EDICION_NumEdicion`)
    REFERENCES `mydb`.`EDICION` (`LIBROS_ISBN` , `NumEdicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RESERVA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RESERVA` (
  `CLIENTE_DNI` VARCHAR(45) NOT NULL,
  `FISICO_EDICION_LIBROS_ISBN` INT NOT NULL,
  `FISICO_EDICION_NumEdicion` INT NOT NULL,
  `ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLIENTE_DNI`, `FISICO_EDICION_LIBROS_ISBN`, `FISICO_EDICION_NumEdicion`, `ID`),
  INDEX `fk_CLIENTE_has_FISICO_FISICO2_idx` (`FISICO_EDICION_LIBROS_ISBN` ASC, `FISICO_EDICION_NumEdicion` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_FISICO_CLIENTE2_idx` (`CLIENTE_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_FISICO_CLIENTE2`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `mydb`.`CLIENTE` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLIENTE_has_FISICO_FISICO2`
    FOREIGN KEY (`FISICO_EDICION_LIBROS_ISBN` , `FISICO_EDICION_NumEdicion`)
    REFERENCES `mydb`.`FISICO` (`EDICION_LIBROS_ISBN` , `EDICION_NumEdicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLEADO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `HFinal` TIME NULL,
  `HInicio` TIME NULL,
  `Salario` DOUBLE NULL,
  `Jornada` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RESERVA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RESERVA` (
  `CLIENTE_DNI` VARCHAR(45) NOT NULL,
  `FISICO_EDICION_LIBROS_ISBN` INT NOT NULL,
  `FISICO_EDICION_NumEdicion` INT NOT NULL,
  `ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLIENTE_DNI`, `FISICO_EDICION_LIBROS_ISBN`, `FISICO_EDICION_NumEdicion`, `ID`),
  INDEX `fk_CLIENTE_has_FISICO_FISICO2_idx` (`FISICO_EDICION_LIBROS_ISBN` ASC, `FISICO_EDICION_NumEdicion` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_FISICO_CLIENTE2_idx` (`CLIENTE_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_FISICO_CLIENTE2`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `mydb`.`CLIENTE` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLIENTE_has_FISICO_FISICO2`
    FOREIGN KEY (`FISICO_EDICION_LIBROS_ISBN` , `FISICO_EDICION_NumEdicion`)
    REFERENCES `mydb`.`FISICO` (`EDICION_LIBROS_ISBN` , `EDICION_NumEdicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `ID` VARCHAR(45) NOT NULL,
  `CLIENTE_DNI` VARCHAR(45) NOT NULL,
  `EMPLEADO_DNI1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `CLIENTE_DNI`),
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_DNI` ASC) VISIBLE,
  INDEX `fk_PEDIDO_EMPLEADO1_idx` (`EMPLEADO_DNI1` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `mydb`.`CLIENTE` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PEDIDO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_DNI1`)
    REFERENCES `mydb`.`EMPLEADO` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERTENECE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PERTENECE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PERTENECE` (
  `EDICION_LIBROS_ISBN` INT NOT NULL,
  `EDICION_NumEdicion` INT NOT NULL,
  `PEDIDO_ID` VARCHAR(45) NOT NULL,
  `PEDIDO_CLIENTE_DNI` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`, `PEDIDO_ID`, `PEDIDO_CLIENTE_DNI`),
  INDEX `fk_EDICION_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_ID` ASC, `PEDIDO_CLIENTE_DNI` ASC) VISIBLE,
  INDEX `fk_EDICION_has_PEDIDO_EDICION1_idx` (`EDICION_LIBROS_ISBN` ASC, `EDICION_NumEdicion` ASC) VISIBLE,
  CONSTRAINT `fk_EDICION_has_PEDIDO_EDICION1`
    FOREIGN KEY (`EDICION_LIBROS_ISBN` , `EDICION_NumEdicion`)
    REFERENCES `mydb`.`EDICION` (`LIBROS_ISBN` , `NumEdicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EDICION_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_ID` , `PEDIDO_CLIENTE_DNI`)
    REFERENCES `mydb`.`PEDIDO` (`ID` , `CLIENTE_DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENTREGA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ENTREGA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ENTREGA` (
  `CLIENTE_DNI` VARCHAR(45) NOT NULL,
  `EDICION_LIBROS_ISBN` INT NOT NULL,
  `EDICION_NumEdicion` INT NOT NULL,
  `Cantidad` INT NULL,
  PRIMARY KEY (`CLIENTE_DNI`, `EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`),
  INDEX `fk_CLIENTE_has_EDICION_EDICION1_idx` (`EDICION_LIBROS_ISBN` ASC, `EDICION_NumEdicion` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_EDICION_CLIENTE1_idx` (`CLIENTE_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_EDICION_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `mydb`.`CLIENTE` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLIENTE_has_EDICION_EDICION1`
    FOREIGN KEY (`EDICION_LIBROS_ISBN` , `EDICION_NumEdicion`)
    REFERENCES `mydb`.`EDICION` (`LIBROS_ISBN` , `NumEdicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`LIBROS`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`LIBROS` (`ISBN`, `Título`, `Autor`, `Género`, `Editorial`, `Precio`, `FechaPublicacion`) VALUES (1234, 'Harry Potter', 'J.K', 'Fantástico', 'Anónima', NULL, NULL);
INSERT INTO `mydb`.`LIBROS` (`ISBN`, `Título`, `Autor`, `Género`, `Editorial`, `Precio`, `FechaPublicacion`) VALUES (2468, 'Percy Jackson', 'Saúl', 'Acción', 'Santillana', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`CLIENTE`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`CLIENTE` (`DNI`, `NumContacto`, `FechaNac`, `Nombre`, `Dirección`, `LibrosExtraibles`) VALUES ('04576453', 696216394, '06/01/99', 'Sheyla', 'Avenida Pico Teide', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`EDICION`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`EDICION` (`LIBROS_ISBN`, `NumEdicion`, `Stock`, `CLIENTE_DNI_recibe`) VALUES (1234, 1, 10, '79063836');
INSERT INTO `mydb`.`EDICION` (`LIBROS_ISBN`, `NumEdicion`, `Stock`, `CLIENTE_DNI_recibe`) VALUES (2468, 4, 15, '04576453');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`DIGITAL`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DIGITAL` (`EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`, `Valoracion`, `Opiniones`) VALUES (1234, 1, 10, 'Está muy bien');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`FISICO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`FISICO` (`EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`) VALUES (1234, 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`EMPLEADO` (`DNI`, `Nombre`, `HFinal`, `HInicio`, `Salario`, `Jornada`, `Apellidos`) VALUES ('78854723', 'Pepe', '19', '14', 15000, 'Completa', 'López');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`RESERVA`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`RESERVA` (`CLIENTE_DNI`, `FISICO_EDICION_LIBROS_ISBN`, `FISICO_EDICION_NumEdicion`, `ID`) VALUES ('04576453', 2468, 5, '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`PEDIDO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`PEDIDO` (`ID`, `CLIENTE_DNI`, `EMPLEADO_DNI1`) VALUES ('3', '79063836', '78854773');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`PERTENECE`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`PERTENECE` (`EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`, `PEDIDO_ID`, `PEDIDO_CLIENTE_DNI`) VALUES (1234, 5, '1', '04576453');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ENTREGA`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ENTREGA` (`CLIENTE_DNI`, `EDICION_LIBROS_ISBN`, `EDICION_NumEdicion`, `Cantidad`) VALUES ('04576454', 1234, 1, 6);

COMMIT;

